// <auto-generated />
using System;
using Factorio.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Factorio.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002065834_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Factorio.Domain.Entities.Blueprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlueprintString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenshotPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Blueprints", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            BlueprintString = "SAMPLE-BLUEPRINT-STRING",
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Placeholder entry for testing",
                            Title = "Sample blueprint"
                        });
                });

            modelBuilder.Entity("Factorio.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CraftTime")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StackSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stats")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InternalName")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Intermediate products",
                            CraftTime = 3.2000000000000002,
                            Description = "Basic building material made by smelting iron ore.",
                            InternalName = "iron-plate",
                            Name = "Iron plate",
                            ProductAmount = 1,
                            StackSize = 100,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Category = "Intermediate products",
                            CraftTime = 3.2000000000000002,
                            InternalName = "copper-plate",
                            Name = "Copper plate",
                            ProductAmount = 1,
                            StackSize = 100
                        },
                        new
                        {
                            Id = 3,
                            Category = "Intermediate products",
                            CraftTime = 0.5,
                            InternalName = "copper-cable",
                            Name = "Copper cable",
                            ProductAmount = 2,
                            StackSize = 200
                        },
                        new
                        {
                            Id = 4,
                            Category = "Intermediate products",
                            CraftTime = 0.5,
                            InternalName = "electronic-circuit",
                            Name = "Electronic circuit",
                            ProductAmount = 1,
                            StackSize = 200
                        });
                });

            modelBuilder.Entity("Factorio.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("RecipeIngredients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1,
                            IngredientItemId = 2,
                            ItemId = 3
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1,
                            IngredientItemId = 1,
                            ItemId = 4
                        },
                        new
                        {
                            Id = 3,
                            Amount = 3,
                            IngredientItemId = 3,
                            ItemId = 4
                        });
                });

            modelBuilder.Entity("Factorio.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user1@test.com",
                            Name = "Test User",
                            PasswordHash = "$2b$11$GIeYTa5Uz6zPLI2AwbkJAOhB6eVEW0P6YEnEV6PgGtO5wTWbeffwW"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user2@test.com",
                            Name = "Test User 2",
                            PasswordHash = "$2b$11$IVm8leFGjvB9x4NoS29XhOU4oKZnD.mXxcMDOyptJncJlGlBpwPKm"
                        });
                });

            modelBuilder.Entity("Factorio.Domain.Entities.UserAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminComment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Actions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionDetails = "Thin wire used in electronic circuits and power poles.",
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 3,
                            Status = "Pending",
                            Type = "Add",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActionDetails = "Basic building material made by smelting iron ore.",
                            AdminComment = "Looks good",
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 1,
                            Status = "Approved",
                            Type = "Edit",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Factorio.Domain.Entities.Blueprint", b =>
                {
                    b.HasOne("Factorio.Domain.Entities.User", "Author")
                        .WithMany("Blueprints")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Factorio.Domain.Entities.Item", b =>
                {
                    b.HasOne("Factorio.Domain.Entities.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Factorio.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("Factorio.Domain.Entities.Item", "IngredientItem")
                        .WithMany("UsedIn")
                        .HasForeignKey("IngredientItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Factorio.Domain.Entities.Item", "Item")
                        .WithMany("Ingredients")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientItem");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Factorio.Domain.Entities.UserAction", b =>
                {
                    b.HasOne("Factorio.Domain.Entities.Item", "Item")
                        .WithMany("Actions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Factorio.Domain.Entities.User", "User")
                        .WithMany("Actions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Factorio.Domain.Entities.Item", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Ingredients");

                    b.Navigation("UsedIn");
                });

            modelBuilder.Entity("Factorio.Domain.Entities.User", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Blueprints");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
